## Various DataTypes in Python

### Numbers

# Python Tutorial

## Welcome to Python Tutorial


- Datatype

In [ ]:
1+1

In [ ]:
4*5

In [ ]:
2*10

In [ ]:
10/2

In [ ]:
10%2

In [ ]:
10**2

In [ ]:
##Check the Data types

In [ ]:
type(True)

In [ ]:
type("Hello")

### Strings

In [ ]:
"Hello"

In [ ]:
'Hi satish'

In [ ]:
type("Satish")

### Variable Assigment

In [ ]:
# syntax
# var_name=values

a=10

In [ ]:
type(a)

In [ ]:
a='Sat'

In [ ]:
type(a)

In [ ]:
# Mathematical operation with Variable Assigment

# Examples of Arithmetic Operator
a = 9
b = 2

# Addition of numbers
add = a + b

# Subtraction of numbers
sub = a - b

# Multiplication of number
mul = a * b

# Division(float) of number
div1 = a / b

# Division(floor) of number
div2 = a // b

# Modulo of both number
mod = a % b

# Power
p = a ** b

# print results
print(add)
print(sub)
print(mul)
print("Result of Division(float) is :{}".format(div1))
print(div2)
print(mod)
print(p)

In [ ]:
# Examples of Relational Operators
a = 13
b = 33

# a > b is False
print(a > b)

# a < b is True
print(a < b)

# a == b is False
print(a == b)

# a != b is True
print(a != b)

# a >= b is False
print(a >= b)

# a <= b is True
print(a <= b)

In [ ]:
# Examples of Bitwise operators
a = 8
b = 4

# Print bitwise AND operation
print(a & b)

# Print bitwise OR operation
print(a | b)

# Print bitwise NOT operation
print(~4)

# print bitwise XOR operation
print(a ^ b)

# print bitwise right shift operation
print(a >> 2)

# print bitwise left shift operation
print(a << 2)

In [ ]:
# Examples of Logical Operator
a = True
b = True

# Print a and b is False
print(a and b)

# Print a or b is True
print(a or b)

# Print not a is False
print(not a)

In [ ]:
# Examples of Membership operator
x = 'BSC in KLETECH'
y = {3:'a',4:'b'}


print('C' in x)

print('KLE' not in x)

print('BSC' not in x)

print(3 in y)

print('b' in y)

In [ ]:
# Examples of Identity operators
a1 = 3
b1 = 3
a2 = 'SatforGee'
b2 = 'SatforGee'
a3 = [1,2,3]
b3 = [1,2,3]


print(a1 is not b1)


print(a2 is b2)

# Output is False, since lists are mutable.
print(a3 is b3)

In [ ]:
## Various Ways of Printing

print("Hello")

In [ ]:
first_name='Satish'
last_name='chikkamath'

In [ ]:
print("My first name is {} and last name is {}".format(first_name,last_name))

In [ ]:
print("My First name is {first} and last name is {last}".format(last=last_name,first=first_name))

In [ ]:
a=8
b=8
a<=b

In [ ]:
a=10
b=1
a**=b
print(a)

In [ ]:
#Arrays: LIST-TUPLE-SET-DICTIONARY
Potter=["Harry","Wizard","Magic"]
print(Potter[1])

In [ ]:
#Loop through a LIST
Potter=["Harry","Wizard","Dumbeldore"]
for x in Potter:
    print(Potter)

In [ ]:
#Check If Item Exists
Potter=["Harry","Wizard","Dumbeldore","S","Z","Hogwarts"]
if "R" in Potter:
    print("YES, 'R' is in Potter")
else:
    print("NO")

In [ ]:
#List Length
thislist = ["apple", "banana", "cherry"]
print(len(thislist))

In [ ]:
list1 = ["apple", "banana", "cherry"]
list2 = [1, 5, 7, 9, 3]
list3 = [True, False, False]
print(type(list1))

In [ ]:
#Let's check the statement that lists are the ordered.
a = [1,2,"Peter",4.50,"Ricky",5,6]  
b = [1,2,5,"Peter",4.50,"Ricky",6]  
a == b

In [ ]:
#Let's have a look at the list example in detail.
emp = ["John", 102, "USA"]     
Dep1 = ["CS",10]  
Dep2 = ["IT",11]    
HOD_CS = [10,"Mr. Holding"]    
HOD_IT = [11, "Mr. Bewon"]    
print("printing employee data...")    
print("Name : %s, ID: %d, Country: %s"%(emp[0],emp[1],emp[2]))    
print("printing departments...")   
print("Department 1:\nName: %s, ID: %d\nDepartment 2:\nName: %s, ID: %s"%(Dep1[0],Dep2[1],Dep2[0],Dep2[1]))    
print("HOD Details ....")    
print("CS HOD Name: %s, Id: %d"%(HOD_CS[1],HOD_CS[0]))    
print("IT HOD Name: %s, Id: %d"%(HOD_IT[1],HOD_IT[0]))    
print(type(emp),type(Dep1),type(Dep2),type(HOD_CS),type(HOD_IT))  

#In the above example, we have created the lists which consist of the 
#employee and department details and printed the corresponding details.

In [ ]:
#List indexing and splitting
#The indexing is processed in the same way as it happens with the strings. 
#The elements of the list can be accessed by using the slice operator [].
HI=[1,5,2,3,4]
print(HI[0:2])

In [ ]:
#list_varible(start:stop:step)  
list = [1,2,3,4,5,6,7]  
print(list[0])  
print(list[1])  
print(list[2])  
print(list[3])  
# Slicing the elements  
print(list[0:6])  
# By default the index value is 0 so its starts from the 0th element and go for index -1.  
print(list[:])  
print(list[2:5])  
print(list[1:6:2])

In [ ]:
#Negative extraction
list = [1,2,3,4,5]  
print(list[-1])  
print(list[-3:])  
print(list[:-1])  
print(list[-3:-1])

In [ ]:
#Updating List values
list = [1, 2, 3, 4, 5, 6]     
print(list)     
# It will assign value to the value to the second index   
list[2] = 10   
print(list)    
# Adding multiple-element   
list[1:3] = [89, 78]     
print(list)   
# It will add value at the end of the list  
list[-1] = 25  
print(list)

In [ ]:
#Iterating a List
list = ["John", "David", "James", "Jonathan"]    
for i in list:   
    # The i variable will iterate over the elements of the List and contains each element in each iteration.     
    print(i)

In [ ]:
#Adding elements to the list
#Declaring the empty list  
l =[]  
#Number of elements will be entered by the user    
n = int(input("Enter the number of elements in the list:"))  
# for loop to take the input  
for i in range(0,n):     
    # The input is taken from the user and added to the list as the item  
    l.append(input("Enter the item:"))     
print("printing the list items..")   
# traversal loop to print the list items    
for i in l:   
    print(i, end = "  ")

In [ ]:
#Removing elements from the list
list = [0,1,2,3,4]     
print("printing original list: ");    
for i in list:    
    print(i,end=" ")    
list.remove(2)    
print("\nprinting the list after the removal of first element...")    
for i in list:    
    print(i,end=" ")

In [ ]:
#Example: 1- Write the program to remove the duplicate element of the list.

In [ ]:
#Example:2- Write a program to find the sum of the element in the list.